using System.Collections.Generic;

namespace AwesomeApp.Web.ApiModels
{
    // ApiModel DTOs are used by ApiController classes and are typically kept in a side-by-side folder
    public class ShoppingListDTO : CreateShoppingListDTO
    {
        public int Id { get; set; }
        public List<ItemDTO> Items = new();
    }

    // Creation DTOs should not include an ID if the ID will be generated by the back end
    public class CreateShoppingListDTO
    {
        public string Name { get; set; }
    }
}
